 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  nextqa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/train.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/train.json
        val:
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/val.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/val.json
        test:
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/val.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/NExT_QA/nextqa/val.json
      videos:
        storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/raw/NExT
